let data;let activeTab='profile';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function boot(){const session=await fetch('/api/session',{cache:'no-store'}).then(r=>r.json()).catch(()=>({ok:false}));if(session.ok)return openEditor();$('#loginForm').addEventListener('submit',login)}
async function login(ev){ev.preventDefault();$('#loginStatus').textContent='Signing in…';const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});const out=await r.json().catch(()=>({}));if(!r.ok){$('#loginStatus').textContent=out.error||'Login failed';return}$('#loginStatus').textContent='';openEditor()}
async function openEditor(){$('#loginPanel').hidden=true;$('#editorShell').hidden=false;data=await fetch('/api/content',{cache:'no-store'}).then(r=>r.json());bindShell();renderTab()}
function bindShell(){$$('.editor-nav [data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;$$('.editor-nav [data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderTab()});$('#saveButton').onclick=save;$('#logoutButton').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.reload()}}
function renderTab(){const titles={profile:'Profile & story',timeline:'Timeline',works:'Selected works',research:'Research & contact',theme:'Theme'};$('#tabTitle').textContent=titles[activeTab];const root=$('#editorContent');if(activeTab==='profile')root.innerHTML=renderProfile();if(activeTab==='timeline')root.innerHTML=renderTimeline();if(activeTab==='works')root.innerHTML=renderWorks();if(activeTab==='research')root.innerHTML=renderResearch();if(activeTab==='theme')root.innerHTML=renderTheme();bindFields();bindUploads();bindDynamicActions()}
function renderProfile(){return `<section class="editor-card"><h3>Hero</h3><div class="form-grid">${field('Eyebrow','profile.eyebrow',data.profile.eyebrow)}${field('Name','profile.name',data.profile.name)}${area('Headline','profile.headline',data.profile.headline,true)}${area('Introduction','profile.intro',data.profile.intro,true)}${mediaField('Profile image','profile.profileImage',data.profile.profileImage,'profile')}${field('Image alt text','profile.profileImageAlt',data.profile.profileImageAlt)}</div></section><section class="editor-card"><h3>Trajectory chapters</h3>${data.chapters.map((c,i)=>`<div class="editor-card"><div class="form-grid">${field('Period',`chapters.${i}.period`,c.period)}${field('Accent label',`chapters.${i}.accent`,c.accent)}${area('Title',`chapters.${i}.title`,c.title,true)}${area('Body',`chapters.${i}.body`,c.body,true)}</div></div>`).join('')}</section>`}
function renderTimeline(){return `<section class="editor-card"><div class="form-grid">${area('Timeline introduction','timelineIntro',data.timelineIntro,true)}</div></section><div class="add-row"><button data-add="timeline">+ Add timeline entry</button></div>${data.timeline.map((x,i)=>`<section class="editor-card"><h3>${esc(x.year)} · ${esc(x.title)}</h3><div class="form-grid">${field('Year',`timeline.${i}.year`,x.year)}${field('Type / filter',`timeline.${i}.type`,x.type)}${field('Title',`timeline.${i}.title`,x.title,true)}${field('Organization',`timeline.${i}.organization`,x.organization,true)}${area('Description',`timeline.${i}.description`,x.description,true)}${field('Link label',`timeline.${i}.linkLabel`,x.linkLabel)}${field('Link URL',`timeline.${i}.linkUrl`,x.linkUrl)}${mediaField('Image',`timeline.${i}.image`,x.image,`timeline-${i}`)}${field('Image alt text',`timeline.${i}.imageAlt`,x.imageAlt)}</div><div class="item-actions"><button class="danger" data-remove="timeline" data-index="${i}">Remove</button></div></section>`).join('')}`}
function renderWorks(){return `<div class="add-row"><button data-add="works">+ Add work</button></div>${data.works.map((x,i)=>`<section class="editor-card"><h3>${esc(x.title)}</h3><div class="form-grid">${field('Title',`works.${i}.title`,x.title,true)}${field('Category',`works.${i}.category`,x.category)}${area('Description',`works.${i}.description`,x.description,true)}${field('Link label',`works.${i}.linkLabel`,x.linkLabel)}${field('Link URL',`works.${i}.linkUrl`,x.linkUrl)}${mediaField('Image',`works.${i}.image`,x.image,`work-${i}`)}${field('Image alt text',`works.${i}.imageAlt`,x.imageAlt)}</div><div class="item-actions"><button class="danger" data-remove="works" data-index="${i}">Remove</button></div></section>`).join('')}`}
function renderResearch(){const r=data.research,c=data.contact;return `<section class="editor-card"><h3>Research</h3><div class="form-grid">${field('Eyebrow','research.eyebrow',r.eyebrow)}${area('Statement','research.statement',r.statement,true)}${area('Body','research.body',r.body,true)}</div></section><section class="editor-card"><h3>Contact</h3><div class="form-grid">${field('Heading','contact.heading',c.heading,true)}${area('Body','contact.body',c.body,true)}${field('Email','contact.email',c.email)}${field('LinkedIn','contact.linkedin',c.linkedin)}${field('GitHub','contact.github',c.github)}</div></section>`}
function renderTheme(){const t=data.theme;return `<section class="editor-card"><h3>Global visual theme</h3><div class="theme-swatches">${color('Background','theme.background',t.background)}${color('Surface','theme.surface',t.surface)}${color('Ink','theme.ink',t.ink)}${color('Muted text','theme.muted',t.muted)}${color('Accent','theme.accent',t.accent)}${color('Lines','theme.line',t.line)}</div></section><section class="editor-card"><h3>Typography</h3><div class="form-grid">${field('Display font stack','theme.fontDisplay',t.fontDisplay,true)}${field('Body font stack','theme.fontBody',t.fontBody,true)}${field('Technical font stack','theme.fontTechnical',t.fontTechnical,true)}</div></section>`}
function field(label,path,value,full=false){return `<label class="field ${full?'full':''}">${label}<input data-path="${path}" value="${attr(value||'')}"></label>`}
function area(label,path,value,full=false){return `<label class="field ${full?'full':''}">${label}<textarea data-path="${path}">${esc(value||'')}</textarea></label>`}
function color(label,path,value){return `<label class="field">${label}<input type="color" data-path="${path}" value="${attr(value)}"><input data-path="${path}" value="${attr(value)}"></label>`}
function mediaField(label,path,value,id){return `<label class="field full">${label}<div class="media-row"><input data-path="${path}" value="${attr(value||'')}" placeholder="Image URL or upload"><label class="upload-btn">Upload image<input type="file" data-upload-path="${path}" data-upload-id="${id}" accept="image/*"></label></div>${value?`<img class="thumb" src="${attr(value)}" alt="Preview">`:''}</label>`}
function bindFields(){$$('[data-path]').forEach(el=>el.addEventListener('input',()=>{setPath(data,el.dataset.path,el.value);if(el.type==='color')$$('[data-path="'+el.dataset.path+'"]').forEach(x=>{if(x!==el)x.value=el.value})}))}
function bindUploads(){$$('[data-upload-path]').forEach(el=>el.onchange=async()=>{const file=el.files?.[0];if(!file)return;status('Uploading image…');const url=await upload(file);if(!url)return;setPath(data,el.dataset.uploadPath,url);status('Image uploaded. Save changes to publish.');renderTab()})}
async function upload(file){const r=await fetch(`/api/upload?filename=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});const out=await r.json().catch(()=>({}));if(!r.ok){status(out.error||'Upload failed',true);return''}return out.url}
function bindDynamicActions(){$$('[data-add]').forEach(b=>b.onclick=()=>{if(b.dataset.add==='timeline')data.timeline.unshift({year:'2026',type:'Project',title:'New entry',organization:'',description:'',linkLabel:'',linkUrl:'',image:'',imageAlt:''});else data.works.push({title:'New work',category:'Project',description:'',image:'',imageAlt:'',linkLabel:'',linkUrl:''});renderTab()});$$('[data-remove]').forEach(b=>b.onclick=()=>{data[b.dataset.remove].splice(+b.dataset.index,1);renderTab()})}
async function save(){status('Saving…');const r=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json().catch(()=>({}));if(!r.ok){status(out.error||'Save failed',true);return}status('Saved. The public site now uses this revision.')}
function status(msg,error=false){$('#saveStatus').textContent=msg;$('#saveStatus').style.color=error?'#9a3026':'var(--muted)'}
function setPath(obj,path,value){const parts=path.split('.');let cur=obj;for(let i=0;i<parts.length-1;i++)cur=cur[parts[i]];cur[parts.at(-1)]=value}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function attr(v=''){return esc(v)}boot();